Repository the-kingdoms/eollugage-fe, pull requests merged in 2024-12, with the labels that each got.

#92 Docs : 홈 주요 기능 설명 추가
  README.md
  scripts/generateLinkSettingFile.js
  src/app/join/page.tsx
  src/features/mypage/ui/BottomSheet.tsx
  src/shared/ui/ToastMessage.tsx
  src/widgets/home/ui/HomeWidgetClient.tsx
  src/widgets/home/ui/NoticeWidget.tsx
  src/widgets/home/ui/OrderWidget.tsx
  src/widgets/home/ui/TodayWork.tsx
  src/widgets/index.ts
  src/widgets/join/ui/LoginButton.tsx
  src/widgets/join/ui/SignupStore.tsx
  src/widgets/join/ui/UserProfile.tsx
  src/widgets/mypage/ui/MyPageWidget.tsx
  src/widgets/mypage/ui/PositionWidget.tsx
  src/widgets/setting/ui/QuitWidget.tsx
  src/widgets/setting/ui/SettingWidget.tsx
  src/widgets/upload-image/model/useHandleStoreImage.ts
  src/widgets/upload-image/ui/ImageContainer.tsx
  src/widgets/upload-image/ui/ImageControlButtons.tsx
  src/widgets/upload-image/ui/ImageErrorDialog.tsx
  src/widgets/upload-image/ui/ImageSkipDialog.tsx
  src/widgets/upload-image/ui/ImageTitle.tsx
  src/widgets/upload-image/ui/UploadImageClient.tsx
  src/widgets/work-management/ui/AttendanceFormClient.tsx
  src/widgets/work-management/ui/AttendanceRegister.tsx
  src/widgets/work-management/ui/MemberSelector.tsx
  src/widgets/work-management/ui/WorkManagementOwnerClient.tsx
Labels: documentation

#91 docs: 근무 관리 기능 설명 추가
  README.md
Labels: documentation

#96 FIX : 초기화면 애니메이션 Layer 오류 수정
  src/app/page.module.css
Labels: fix

#94 FEAT: #89 회원가입 인증번호 관련 ui를 추가한다
  src/app/join/page.tsx
  src/widgets/join/api/postLogin.ts
  src/widgets/join/api/postOTP.ts
  src/widgets/join/atoms/joinAtoms.ts
  src/widgets/join/model/usePostLogin.ts
  src/widgets/join/model/usePostOTP.ts
  src/widgets/join/ui/OTP/OTPField.tsx
  src/widgets/join/ui/OTP/TextFieldSkeleton.tsx
  src/widgets/join/ui/SignupName.tsx
Labels: feature
